### ISSUE TITLE
Реализовать базовый компонент кнопки

### ISSUE THREAD

**Issue by artem-zaitsev** [boostgrade/wtgt_gamma#3]
## Описание задачи

Реализовать кнопку, которая будет использоваться повсеместно в приложении.

## Требования (если есть)

* [ ] Кнопка должна иметь три состояния, которые будут управляться с помощью
конструктора. 
----
Состояния кнопки:
* [ ] Активна
* [ ] Неактивна
* [ ] Индикатор загрузки
----

* [ ] На вход кнопке передается текст
* [ ] На вход кнопке передается обработчик нажатия.

## Артефакты

Дизайн: https://www.figma.com/file/8wRDN0M82bIuRZS6Uomv8X/Where-to-go-today%3F?node-id=17%3A466

**Comment by Veselchak-U** [comment]
@dkrutskikh ,  "На вход кнопке передается: текст, обработчик нажатия." - это исчерпывающие входные параметры? 
Т.е. показывать индикатор загрузки нужно по наличию текста на входе или для этого можно добавить отдельный входной параметр?
