### ISSUE TITLE
Реализовать интерцептор для обработки ошибок сервера

### ISSUE THREAD

**Issue by artem-zaitsev** [boostgrade/wtgt_gamma#4]
## Описание задачи

Нам необходимо приводит различные ошибки сервера к внутренним Exception, которые будет обрабатывать класс ErrorHandler. 

Для этого можно использовать Dio и Interceptor. 

Также необходимо использовать класс ServerErrorMapper дописать в нем логику приведения ошибок. На этот класс уже написан тест, так что можно проверить работу класса, запустив его.

## Требования
Необходимо написать Interceptors, которые делают следующее:

* [ ] Обрабатывает HTTP код и приводит его к Exception либо передает управление следующему Interceptor. 
* [ ] Если HTTP код 400 - парсит тело ошибки и по внутреннему коду бросает новый кастомный Exception. 
* [ ] Если пришла 401 - оставить TODO с сообщение о необходимости попытки перезапросить токен, и вывести сообщение в консоль.

## Артефакты

- https://pub.dev/packages/dio#interceptors

**Comment by beersheba** [comment]
@dkrutskikh не совсем понятно сколько Interceptors здесь требуется. нужно создать по отдельному интерцептору для 400, 401 и тд? или можно ли обойтись одним, который будет выполнять всю обработку ошибок?
